// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmhxygkllzhokoeisjop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtaHh5Z2tsbHpob2tvZWlzam9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2ODg2MzMsImV4cCI6MjA1ODI2NDYzM30.eailQLsKkhnmNeqzZrlZjKPzBIZvRIzmQ6VzfaL8Sew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);